### ISSUE TITLE
Using third party ORMs

### ISSUE THREAD

**Issue by Tarabyte** [zandoan/turing-fullstack#1]
Please clarify if it is allowed to use third party ORMs (for example Sequelize or even Loopback) when implementing the challenge.

If the answer is yes is it mandatory to use provided stored procedures to interact with the DB or ORM generated operations for CRUD would also be an acceptable approach?

**Comment by edertaveiraturing** [comment]
Hi Yury, Yes you can use any ORM like Sequelize, Bookshelf.js, Objection.js or even Loopback.
You can use or not stored procedures, it isn't mandatory.

**Comment by Tarabyte** [comment]
@edertaveiraturing Thank you!
